package org.greencodeinitiative.creedengo.integration.tests.profile;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class ProfileMetadataTest {

    // -----------------------------------------------------------------------
    // Canonical constructor and record accessors
    // -----------------------------------------------------------------------

    @Test
    void testConstructorAndAccessors() {
        ProfileMetadata metadata = new ProfileMetadata("creedengo way", "java", List.of("GCI1", "GCI2"));
        assertEquals("creedengo way",            metadata.name());
        assertEquals("java",                     metadata.language());
        assertEquals(List.of("GCI1", "GCI2"),    metadata.ruleKeys());
    }

    @Test
    void testConstructorWithNullName() {
        ProfileMetadata metadata = new ProfileMetadata(null, "java", List.of());
        assertNull(metadata.name());
    }

    @Test
    void testConstructorWithNullLanguage() {
        ProfileMetadata metadata = new ProfileMetadata("profile", null, List.of());
        assertNull(metadata.language());
    }

    @Test
    void testConstructorWithNullRuleKeys() {
        ProfileMetadata metadata = new ProfileMetadata("profile", "java", null);
        assertNull(metadata.ruleKeys());
    }

    @Test
    void testConstructorWithEmptyRuleKeys() {
        ProfileMetadata metadata = new ProfileMetadata("profile", "java", Collections.emptyList());
        assertTrue(metadata.ruleKeys().isEmpty());
    }

    @Test
    void testConstructorWithSingleRuleKey() {
        ProfileMetadata metadata = new ProfileMetadata("profile", "java", List.of("GCI42"));
        assertEquals(1,       metadata.ruleKeys().size());
        assertEquals("GCI42", metadata.ruleKeys().get(0));
    }

    // -----------------------------------------------------------------------
    // equals & hashCode — natively generated by the record
    // -----------------------------------------------------------------------

    @Test
    void testEqualsSameValues() {
        ProfileMetadata a = new ProfileMetadata("creedengo way", "java", List.of("GCI1", "GCI2"));
        ProfileMetadata b = new ProfileMetadata("creedengo way", "java", List.of("GCI1", "GCI2"));
        assertEquals(a, b);
        assertEquals(a.hashCode(), b.hashCode());
    }

    @Test
    void testEqualsDifferentName() {
        ProfileMetadata a = new ProfileMetadata("name-A", "java", Collections.emptyList());
        ProfileMetadata b = new ProfileMetadata("name-B", "java", Collections.emptyList());
        assertNotEquals(a, b);
    }

    @Test
    void testEqualsDifferentLanguage() {
        ProfileMetadata a = new ProfileMetadata("profile", "java",   Collections.emptyList());
        ProfileMetadata b = new ProfileMetadata("profile", "python", Collections.emptyList());
        assertNotEquals(a, b);
    }

    @Test
    void testEqualsDifferentRuleKeys() {
        ProfileMetadata a = new ProfileMetadata("profile", "java", List.of("GCI1"));
        ProfileMetadata b = new ProfileMetadata("profile", "java", List.of("GCI2"));
        assertNotEquals(a, b);
    }

    @Test
    void testEqualsWithNull() {
        ProfileMetadata a = new ProfileMetadata("profile", "java", List.of());
        assertNotEquals(null, a);
    }

    @Test
    void testEqualsWithDifferentType() {
        ProfileMetadata a = new ProfileMetadata("profile", "java", List.of());
        assertNotEquals("a string", a);
    }

    @Test
    void testEqualsAndHashCodeContract() {
        // Java contract: two equal objects must have the same hashCode
        ProfileMetadata a = new ProfileMetadata("x", "java", List.of("GCI1"));
        ProfileMetadata b = new ProfileMetadata("x", "java", List.of("GCI1"));
        assertEquals(a, b);
        assertEquals(a.hashCode(), b.hashCode(),
            "Two equal records must have the same hashCode (Java contract)");
    }

    @Test
    void testHashCodeConsistency() {
        ProfileMetadata a = new ProfileMetadata("creedengo way", "java", List.of("GCI1"));
        assertEquals(a.hashCode(), a.hashCode());
    }

    @Test
    void testHashCodeForNullFields() {
        ProfileMetadata a = new ProfileMetadata(null, null, null);
        assertDoesNotThrow(a::hashCode);
    }

    // -----------------------------------------------------------------------
    // toString — natively generated by the record
    // -----------------------------------------------------------------------

    @Test
    void testToStringContainsFieldValues() {
        ProfileMetadata metadata = new ProfileMetadata("creedengo way", "java", List.of("GCI1", "GCI2"));
        String str = metadata.toString();
        assertTrue(str.contains("creedengo way"), "toString must contain the name");
        assertTrue(str.contains("java"),           "toString must contain the language");
        assertTrue(str.contains("GCI1"),           "toString must contain the ruleKeys");
        assertTrue(str.contains("GCI2"),           "toString must contain the ruleKeys");
    }

    @Test
    void testToStringRecordFormat() {
        // The toString of a Java record follows the format:
        // RecordName[component1=value1, component2=value2, ...]
        ProfileMetadata metadata = new ProfileMetadata("creedengo way", "java", List.of("GCI1"));
        String str = metadata.toString();
        assertEquals(
            "ProfileMetadata[name=creedengo way, language=java, ruleKeys=[GCI1]]",
            str,
            "The toString of a record must follow the format RecordName[field=value, ...]"
        );
    }

    @Test
    void testToStringWithNullFields() {
        ProfileMetadata metadata = new ProfileMetadata(null, null, null);
        String str = metadata.toString();
        assertNotNull(str);
        assertTrue(str.contains("null"));
    }

    // -----------------------------------------------------------------------
    // Record structure
    // -----------------------------------------------------------------------

    @Test
    void testIsRecord() {
        assertTrue(ProfileMetadata.class.isRecord(),
            "ProfileMetadata must be a Java record");
    }

    @Test
    void testRecordComponentCount() {
        assertEquals(3, ProfileMetadata.class.getRecordComponents().length,
            "ProfileMetadata must have exactly 3 components");
    }

    @Test
    void testRecordComponentNames() {
        var components = ProfileMetadata.class.getRecordComponents();
        assertEquals("name",     components[0].getName());
        assertEquals("language", components[1].getName());
        assertEquals("ruleKeys", components[2].getName());
    }

    @Test
    void testRecordHasNoSetters() {
        long setterCount = Arrays.stream(ProfileMetadata.class.getMethods())
            .filter(m -> m.getName().startsWith("set"))
            .count();
        assertEquals(0, setterCount, "A record must not have any setters");
    }

}

